In [11]:
import numpy as np
import tensorflow as tf

In [2]:
tf.__version__

'2.0.0'

In [3]:
# install tensorflow
# !pip install tensorflow==2.0.0

### Import Numpy
행렬을 선언하기 위해 numpy 임포트. 5x5 행렬을 만든다.

In [4]:
import numpy as np

# declare 5 rows and 5 columns of 1s
numpy_array = np.ones([5, 5]) 
print(numpy_array)
print(numpy_array.shape)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(5, 5)


파이썬 리스트에서 numpy 어레이 생성. 행벡터 생성 

In [5]:
numpy_vector = np.asarray([[3.,5.,3.,2.,2.]])
print(numpy_vector)
print(numpy_vector.shape)

[[3. 5. 3. 2. 2.]]
(1, 5)


# 텐서플로 기본연산

### 곱셈하기

In [6]:
tensor = tf.matmul(numpy_array, numpy_vector.T)
print(tensor)

tf.Tensor(
[[15.]
 [15.]
 [15.]
 [15.]
 [15.]], shape=(5, 1), dtype=float64)


### 덧셈하기

In [7]:
tensor_2 = tf.add(tensor, numpy_vector.T)
print(tensor_2)

tf.Tensor(
[[18.]
 [20.]
 [18.]
 [17.]
 [17.]], shape=(5, 1), dtype=float64)


### 브로드캐스팅
벡터와 단일값을 연산

In [8]:
tensor_3 = tf.multiply(tensor_2, 3)
print(tensor_3)

tf.Tensor(
[[54.]
 [60.]
 [54.]
 [51.]
 [51.]], shape=(5, 1), dtype=float64)


# Numpy 어레이와 Tensors
텐서는 numpy 어레이로 변환이 가능하다. (묵시적, 명시적)

In [10]:
tensor_3.numpy()

array([[54.],
       [60.],
       [54.],
       [51.],
       [51.]])

In [12]:
np.add(tensor_3, 9)

array([[63.],
       [69.],
       [63.],
       [60.],
       [60.]])