In [1]:
import tensorflow as tf
from tensorflow import keras
import IPython.display as display
import numpy as np

## 1D Tensor

In [2]:
_a = np.ones(5)
_a = tf.multiply(_a, 1)
print(_a)
_a.shape

tf.Tensor([1. 1. 1. 1. 1.], shape=(5,), dtype=float64)


TensorShape([5])

## 2D Tensor

In [3]:
_b = np.ones([2,5])
_b = tf.multiply(_b, 1)
print(_b)
_b.shape

tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(2, 5), dtype=float64)


TensorShape([2, 5])

## 3D Tensor

In [4]:
img_raw = tf.io.read_file('data/cat.jpg')
repr(img_raw)[0:100]

"<tf.Tensor: id=7, shape=(), dtype=string, numpy=b'\\xff\\xd8\\xff\\xe0\\x00\\x10JFIF\\x00\\x01\\x01\\x00\\x00\\x"

In [5]:
img_tensor = tf.image.decode_image(img_raw)

In [6]:
img_tensor.shape

TensorShape([428, 590, 3])

In [7]:
img_tensor.dtype

tf.uint8

In [8]:
img_final = tf.image.resize(img_tensor, [192, 192])
img_final

<tf.Tensor: id=25, shape=(192, 192, 3), dtype=float32, numpy=
array([[[253.0224 , 253.0224 , 253.0224 ],
        [254.     , 254.     , 254.     ],
        [253.61458, 253.61458, 253.61458],
        ...,
        [253.61458, 253.61458, 253.61458],
        [253.61458, 253.61458, 253.61458],
        [253.61458, 253.61458, 253.61458]],

       [[254.03645, 254.03645, 254.03645],
        [255.     , 255.     , 255.     ],
        [255.     , 255.     , 255.     ],
        ...,
        [255.     , 255.     , 255.     ],
        [255.     , 255.     , 255.     ],
        [255.     , 255.     , 255.     ]],

       [[254.     , 254.     , 254.     ],
        [255.     , 255.     , 255.     ],
        [254.     , 254.     , 254.     ],
        ...,
        [254.     , 254.     , 254.     ],
        [254.     , 254.     , 254.     ],
        [254.     , 254.     , 254.     ]],

       ...,

       [[254.     , 254.     , 254.     ],
        [255.     , 255.     , 255.     ],
        [254.1823 , 

In [9]:
# Normalization " -1 < x < 1 "
img_final = img_final/255.0
img_final

<tf.Tensor: id=27, shape=(192, 192, 3), dtype=float32, numpy=
array([[[0.9922447 , 0.9922447 , 0.9922447 ],
        [0.99607843, 0.99607843, 0.99607843],
        [0.994567  , 0.994567  , 0.994567  ],
        ...,
        [0.994567  , 0.994567  , 0.994567  ],
        [0.994567  , 0.994567  , 0.994567  ],
        [0.994567  , 0.994567  , 0.994567  ]],

       [[0.99622136, 0.99622136, 0.99622136],
        [1.        , 1.        , 1.        ],
        [1.        , 1.        , 1.        ],
        ...,
        [1.        , 1.        , 1.        ],
        [1.        , 1.        , 1.        ],
        [1.        , 1.        , 1.        ]],

       [[0.99607843, 0.99607843, 0.99607843],
        [1.        , 1.        , 1.        ],
        [0.99607843, 0.99607843, 0.99607843],
        ...,
        [0.99607843, 0.99607843, 0.99607843],
        [0.99607843, 0.99607843, 0.99607843],
        [0.99607843, 0.99607843, 0.99607843]],

       ...,

       [[0.99607843, 0.99607843, 0.99607843],
      

In [10]:
img_final.shape

TensorShape([192, 192, 3])

In [11]:
img_final.numpy().min()

0.0

In [12]:
img_final.numpy().max()

1.0

## Slicing

In [13]:
_b[:, :3]

<tf.Tensor: id=31, shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

## Reshape

In [14]:
tf.reshape(_b, [-1])

<tf.Tensor: id=33, shape=(10,), dtype=float64, numpy=array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])>

In [15]:
tf.reshape(_b, [2, 5, 1])

<tf.Tensor: id=35, shape=(2, 5, 1), dtype=float64, numpy=
array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])>